bundle the JS and create NPM Package
mozmeao/trafficcop pull request #2
Opened 2022-06-07 01:10 UTC by nathan-barrett

This PR will allow TrafficCop to be published as a NPM package and be imported directly into bedrock (or wherever else its used)

This PR fixes #1

2022-06-07 01:17 UTC, nathan-barrett commented
Adding a package-lock.json always scares me!
<img width="249" alt="Screen Shot 2022-06-06 at 6 17 19 PM" src="https://user-images.githubusercontent.com/30009669/172275232-48717712-4b2c-42ee-8cc2-8b6cbce78d9c.png">

2022-06-07 23:12 UTC, nathan-barrett commented on package.json
> +    "version": "1.0.1",
updated the version to match what was in the old repo

2022-06-08 09:09 UTC, alexgibson requested changes
A couple of nits / suggestions but everything here looks good to me so far.

I did notice that the `/demo/` pages are broken (possibly something that didn't get transferred over from the old repo?). It would be nice to get the demo pages fixed ans using the compiled `/dist/index.js` file, so that we can manually test changes are working OK.

2022-06-08 09:09 UTC, alexgibson commented on src/package/package.json
> +    "name": "trafficcop",
Question: should name be `@mozmeao/trafficcop`? since we're using an NPM namespace?
```suggestion
    "name": "@mozmeao/trafficcop",
```

2022-06-08 17:26 UTC, merged